create table if not exists public.ejemplos_posts (
    id bigint generated by default as identity primary key,
    marca text not null check (marca in ('GAMER_CAVE', 'DAVIET_GAMING')),
    etiqueta text not null,
    noticia_original text not null,
    post text not null,
    feedback text not null check (feedback in ('bueno', 'malo')),
    fecha_creado timestamptz not null default now()
);

create index if not exists ejemplos_posts_marca_feedback_fecha_idx
    on public.ejemplos_posts (marca, feedback, fecha_creado desc);

alter table public.ejemplos_posts enable row level security;

grant select, insert on table public.ejemplos_posts to anon, authenticated, service_role;
grant usage, select on sequence public.ejemplos_posts_id_seq to anon, authenticated, service_role;

drop policy if exists feedback_read on public.ejemplos_posts;
create policy feedback_read
    on public.ejemplos_posts
    for select
    to anon, authenticated
    using (true);

drop policy if exists feedback_insert on public.ejemplos_posts;
create policy feedback_insert
    on public.ejemplos_posts
    for insert
    to anon, authenticated
    with check (
        marca in ('GAMER_CAVE', 'DAVIET_GAMING')
        and feedback in ('bueno', 'malo')
        and char_length(post) between 1 and 10000
        and char_length(noticia_original) between 1 and 20000
    );
